# Generated by Django 4.2.5 on 2023-09-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_alter_agent_address_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
