# Generated by Django 4.2.5 on 2023-09-29 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_agent_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acccount_name', models.CharField(max_length=50)),
                ('account_balance', models.IntegerField()),
                ('account_rate', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.agent')),
            ],
        ),
    ]
