# Generated by Django 4.2.5 on 2023-10-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='acccount_name',
        ),
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
