# Generated by Django 4.2.5 on 2023-10-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_remove_account_acccount_name_account_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Withdraw_type', models.CharField(blank=True, default='N/A', max_length=20, null=True)),
                ('Withdraw_date', models.DateField()),
                ('Withdraw_amount', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deposit_type', models.CharField(blank=True, default='N/A', max_length=20, null=True)),
                ('Deposit_date', models.DateField()),
                ('Deposit_amount', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.agent')),
            ],
        ),
    ]
